### ISSUE TITLE
it's working in the package ?

### ISSUE THREAD

**Issue by KevinBaiSg** [amilajack/erb-local-fs-read-example#4]

**Comment by amilajack** [comment]
I'm not sure what this means. Can you please clarify the question?

**Comment by KevinBaiSg** [comment]
when I run 'yarn package' to archive a release version and run it. It's can not  found text files  
![image](https://user-images.githubusercontent.com/2813260/52764834-96677d80-305c-11e9-8d4c-80c905da4ecd.png)

**Comment by amilajack** [comment]
Oh I see. Yea, this is an issue that needs to be investigated. I would recommend [importing the file through Webpack like so](https://github.com/amilajack/erb-local-fs-read-example/blob/master/app/components/Home.js#L9)
